#!/usr/bin/env bash

if [ -n "$WINDIR" ]; then
  if command -v pwsh >/dev/null 2>&1; then
    pwsh -File ./.githooks/pre-push.ps1
  else
    echo "Warning: pwsh not found. Skipping."
    exit 0
  fi
else
  bash ./.githooks/pre-push.sh
fi
