#!/usr/bin/env bash

set -euo pipefail

remote_name="$1"
remote_url="$2"

echo -e '\033[31m-----------------------------------------------------\033[0m' >&2
echo -e '\033[31mPUSH REJECTED\033[0m' >&2
echo -e "\033[33mPushing to $remote_name <$remote_url> is not allowed.\033[0m" >&2
echo -e '\033[31m-----------------------------------------------------\033[0m' >&2
exit 1
