# shellcheck disable=SC2148

# Execute code that does not affect the current session in the background.
# Have no effect due to p10k
{
  # Compile the completion dump to increase startup speed.
  zcompdump="${XDG_CACHE_HOME:-$HOME/.cache}/.zcompdump-$USER"
  if [[ -s "$zcompdump" && (! -s "${zcompdump}.zwc" || "$zcompdump" -nt "${zcompdump}.zwc") ]]; then
      zcompile "$zcompdump"
  fi
} &!

# Execute code only if STDERR is bound to a TTY.
# if [[ -o INTERACTIVE && -t 2 ]]; then
#   Print a random, hopefully interesting, adage.
#   if (($+commands[fortune])); then
#       fortune -s | cowsay | lolcat
#   fi
# fi >&2
