# This file is for Git Bash

# gpg-agent
gpg-connect-agent updatestartuptty /bye &>/dev/null

# ssh-agent
ssh_env_cache="$HOME/.ssh/environment-$HOSTNAME"

function _start_ssh_agent {
  # Check if ssh-agent is already running
  if [[ -f "$ssh_env_cache" ]]; then
    . "$ssh_env_cache" >/dev/null

    if [[ -S "$SSH_AUTH_SOCK" ]]; then
      return 0
    fi
  fi

  # start ssh-agent and setup environment
  touch "$ssh_env_cache"
  ssh-agent -s | sed '/^echo/d' >"$ssh_env_cache"
  chmod 600 "$ssh_env_cache"
  . "$ssh_env_cache" >/dev/null
}

# Add a nifty symlink for screen/tmux if agent forwarding is enabled
if [[ -n "$SSH_AUTH_SOCK" && ! -L "$SSH_AUTH_SOCK" ]]; then
  ln -sf "$SSH_AUTH_SOCK" /tmp/ssh-agent-$USERNAME-screen
else
  _start_ssh_agent
fi
