name: 'Dev container'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    # tags:
    #   - '**'

jobs:
  lint:
    name: Dev container lint
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:stable
    defaults:
      run:
        working-directory: ./devcont
    steps:
      - name: Clone dotfiles
        uses: actions/checkout@v3
      - name: ShellCheck
        run: |
          find . -type f -name '*.sh' | xargs shellcheck --external-sources --severity=error
          find . -type f -name '*.sh' | xargs shellcheck --external-sources --severity=style || echo "Shellcheck has some warnings"
