name: 'Test on latest Ubuntu'

on:
  push:
    paths:
      - 'nix/**'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check scripts
        run: |
          find . -type f -name '*.sh' | wc -l
          find . -type f -name '*.sh' | xargs shellcheck --external-sources --severity=error --source-path="${PWD}/nix"
          find . -type f -name '*.sh' | xargs shellcheck --external-sources --severity=style --source-path="${PWD}/nix" || echo "Shellcheck has some warnings"
